### ISSUE TITLE
【问题】dcgm监控指标没有exported_namespace，exported_pod，exported_container等标签

### ISSUE THREAD

**Issue by TymonLee** [4paradigm/k8s-vgpu-scheduler#112]
之前用nvidia自带的一些监控指标，比如 DCGM_FI_DEV_FB_USED 或者 DCGM_FI_DEV_GPU_UTIL，收集metrics的时候是有exported_namespace, exported_pod, exported_container 这些指标的，但是切换使用vGPU之后就没有了。也就是说现在看不到GPU上绑定的Pod信息了。
![image](https://github.com/4paradigm/k8s-vgpu-scheduler/assets/23135265/0742b0bb-930f-4937-8991-bbdabf9b5fdb)
![image](https://github.com/4paradigm/k8s-vgpu-scheduler/assets/23135265/113184b9-0de1-4384-862c-cda5d7cab319)

我看了一下nvidia官方的dcgm-exporter代码，这部分的采集数据好像也是调用的CUDA库，可能是什么库函数调用被劫持了？还是说vgpu设计时就是不会显示绑定到GPU的Pod信息？

**Comment by archlitchi** [comment]
vgpu的监控组件curl http://{scheduler ip}:31993/metrics有对应的监控，可以通过这个来查看

**Comment by TymonLee** [comment]
> vgpu的监控组件curl http://{scheduler ip}:31993/metrics有对应的监控，可以通过这个来查看

嗯，我也注意到了。但是好像只有Pod和GPU Device绑定的信息，就看不到这个Pod分配的显存利用率这样的信息了？比如一张GPU总共有24Gi显存，某个Pod申请分配了12Gi，当前看不到这12Gi显存的使用量，还是只能通过dcgm-exporter看整张卡的显存使用量。

**Comment by archlitchi** [comment]
> > vgpu的监控组件curl http://{scheduler ip}:31993/metrics有对应的监控，可以通过这个来查看
> 
> 嗯，我也注意到了。但是好像只有Pod和GPU Device绑定的信息，就看不到这个Pod分配的显存利用率这样的信息了？比如一张GPU总共有24Gi显存，某个Pod申请分配了12Gi，当前看不到这12Gi显存的使用量，还是只能通过dcgm-exporter看整张卡的显存使用量。

实时使用量可以访问curl http://{gpu node ip}:31992/metrics查看
