### ISSUE TITLE
为什么需要另启动一个kube-scheduler

### ISSUE THREAD

**Issue by haitwang-cloud** [4paradigm/k8s-vgpu-scheduler#127]
我看到都在vgpu-scheduler这个deploy中有下面两个container, 

- kube-scheduler
- gpu-scheduler-extender

gpu-scheduler-extender我看参数是用来做vGPU的扩展的，但是请问这里kube-scheduler的作用是什么呢

**Comment by calvin0327** [comment]
@haitwang-cloud 我的理解就是 kube-scheduler 是作为主调度器，gpu-scheduler-extender 作为它 extender 扩展，这两个 container 组合在一起构成一个完整的调度器（4pd-scheduler）。它跟集群中原生的调度器（defaults-scheduler）是相互独立的。
