### ISSUE TITLE
启用无效求助

### ISSUE THREAD

**Issue by techzhou** [4paradigm/k8s-vgpu-scheduler#17]
容器内nvidia-smi仍为满显存

安装命令 helm install vgpu vgpu-charts/vgpu --set scheduler.kubeScheduler.imageTag=v1.21.5 --set devicePlugin.deviceSplitCount=24 --set scheduler.defaultMem=1000 -n gpu-operator-resources

nv环境

> k8s@node-gpu1:~$ dpkg --get-selections | grep nvidia
libnvidia-cfg1-510:amd64			install
libnvidia-common-510				install
libnvidia-compute-510:amd64			install
libnvidia-compute-510:i386			install
libnvidia-container-tools			install
libnvidia-container1:amd64			install
libnvidia-decode-510:amd64			install
libnvidia-decode-510:i386			install
libnvidia-encode-510:amd64			install
libnvidia-encode-510:i386			install
libnvidia-extra-510:amd64			install
libnvidia-fbc1-510:amd64			install
libnvidia-fbc1-510:i386				install
libnvidia-gl-510:amd64				install
libnvidia-gl-510:i386				install
nvidia-compute-utils-510			install
nvidia-container-toolkit			install
nvidia-dkms-510					install
nvidia-docker2					install
nvidia-driver-510				install
nvidia-kernel-common-510			install
nvidia-kernel-source-510			install
nvidia-modprobe					install
nvidia-prime					install
nvidia-settings					install
nvidia-utils-510				install
xserver-xorg-video-nvidia-510			install

**Comment by techzhou** [comment]
@archlitchi 无用

> root@dl-v1-7b549678b8-ptswm:/# nvidia-smi
[4pdvGPU Msg(23:139919262000960:libvgpu.c:817)]: Initializing...
[4pdvGPU Msg(23:139919262000960:context.c:120)]: vdevices_pci=0000:03:00.0
[4pdvGPU Msg(23:139919262000960:libvgpu.c:834)]: Initialized
Fri Apr 29 06:45:59 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A10          On   | 00000000:03:00.0 Off |                    0 |
|  0%   44C    P0    20W / 150W |    225MiB / 23028MiB |      6%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    100203      C                                     223MiB |
+-----------------------------------------------------------------------------+

**Comment by archlitchi** [comment]
可以发一下容器里面执行env的结果吗

**Comment by zqz199** [comment]
请问问题解决了么，我也按流程走下来发现并没有实现切分显存，还是整块物理gpu的大小
[root@master01 qianzhu]# kubectl exec -n kube-system -t vgpu-memory nvidia-smi
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
[4pdvGPU Msg(7:139841703401280:libvgpu.c:817)]: Initializing...
[4pdvGPU Msg(7:139841703401280:context.c:120)]: vdevices_pci=0000:b5:00.0
[4pdvGPU Msg(7:139841703401280:context.c:120)]: vdevices_pci=0000:b9:00.0
[4pdvGPU Msg(7:139841703401280:libvgpu.c:834)]: Initialized
Fri May  6 11:08:42 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.60.02    Driver Version: 510.60.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:B5:00.0 Off |                  N/A |
| 31%   24C    P2    53W / 250W |    154MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:B9:00.0 Off |                  N/A |
| 31%   24C    P2     3W / 250W |    154MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     30195      C                                     151MiB |
|    1   N/A  N/A     30195      C                                     151MiB |
+-----------------------------------------------------------------------------+

**Comment by techzhou** [comment]
@zqz199 作者说可能是5代驱动接口不一致的问题 只能等他们适配了

**Comment by archlitchi** [comment]
@techzhou @zqz199 新版本已经更新，可以helm repo update之后重新装一下试试，有问题可以加我wx:xuanzong4493

**Comment by techzhou** [comment]
@archlitchi 可以了
