### ISSUE TITLE
关于GPU Node的节点设置问题

### ISSUE THREAD

**Issue by IgerAnes** [4paradigm/k8s-vgpu-scheduler#19]
您好
我看到范例有写说可以透过设置annotation里面的nvidia.com/use-gputype来指定显卡，
[https://github.com/4paradigm/k8s-vgpu-scheduler/blob/master/docs/examples/specify_card_type_to_use.yaml]()
那我需要在node端设定gpu资讯吗?
还是在透过helm安装完vgpu后会自动侦测?
如果不会的话想问一下有没有规范设定格式?
期待您的回覆，
感谢😊😊

**Comment by IgerAnes** [comment]
然后我想请教一下，如果要新增GPU Node到schedular内该对那些项目进行修正?
感谢😊😊

**Comment by archlitchi** [comment]
GPU信息是自动检测的，不需要手动配置，这里gpu-type其实是用字符串匹配的方式进行的，比如你设置V100，就会匹配到所有type里包含“V100"字段的卡，比如“ V100-PCIE-32GB“或者“V100-PCIE-16GB"，当然了，这么做也是有问题的，比如你设置成A10也会匹配到A100，新增GPU Node只需要打上gpu=on的label即可

**Comment by IgerAnes** [comment]
> GPU信息是自动检测的，不需要手动配置，这里gpu-type其实是用字符串匹配的方式进行的，比如你设置V100，就会匹配到所有type里包含“V100"字段的卡，比如“ V100-PCIE-32GB“或者“V100-PCIE-16GB"，当然了，这么做也是有问题的，比如你设置成A10也会匹配到A100，新增GPU Node只需要打上gpu=on的label即可

原来如此 非常感谢😊
