### ISSUE TITLE
vgpu-device-plugin-monitor服务的gpu监控可以接入prometheus监控么？

### ISSUE THREAD

**Issue by Chenyangzh** [4paradigm/k8s-vgpu-scheduler#24]
hi，您好

参考https://zhuanlan.zhihu.com/p/125692899

部署gpu集群监控，感觉可以将vgpu监控导入prometheus。尝试了下建立servicemonitor，但prometheus的target列表无新建的vgpu监控项目。请问如何配置可以使用prometheus监控vgpu资源？以下是我的servicemonitor配置文件。

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  creationTimestamp: "2022-06-01T16:57:54Z"
  generation: 5
  labels:
    app: vgpu-metrics
  name: vgpu-metrics
  namespace: monitoring
  resourceVersion: "674182"
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/servicemonitors/vgpu-metrics
  uid: 06a166be-1142-4153-b06e-fe2691fd858a
spec:
  endpoints:
  - path: /metrics
    port: monitorport
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/component: 4pd-scheduler

**Comment by archlitchi** [comment]
你好，我这里目前只有一个exporter，把它接在prometheus的endpoint上应该就可以用了吧，公司内部也是这么用的，不过具体我不是负责这块的不是很清楚细节哈

**Comment by archlitchi** [comment]
目前支持的endpoint为{GPU node ip}:31992/metrics

**Comment by Chenyangzh** [comment]
感谢回复！照着prometheus模板建立了一个新服务，之后配置了认证token问题解决。
