### ISSUE TITLE
重新安裝後，devicePlugin無法正確創建

### ISSUE THREAD

**Issue by IgerAnes** [4paradigm/k8s-vgpu-scheduler#30]
您好
之前由於系統更新顯示卡驅動
我為重新佈署k8s-vgpu-schedular
schedular佈署沒有問題
但直行到devicePlugin就會出錯
![image](https://user-images.githubusercontent.com/32257146/181672777-29f6cea4-c572-48bc-a9d3-52101e5d491d.png)

顯示以下錯誤資訊
`七  28 17:30:34 workernode kubelet[108628]: E0728 17:30:34.498027  108628 pod_workers.go:919] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"device-plugin\" with PostStartHookError: \"Exec lifecycle hook ([/bin/sh -c mv /usrbin/nvidia-container-runtime /usrbin/nvidia-container-runtime-4pdbackup;cp /k8s-vgpu/bin/nvidia-container-runtime /usrbin/;cp -f /k8s-vgpu/lib/* /usr/local/vgpu/]) for Container \\\"device-plugin\\\" in Pod \\\"vgpu-device-plugin-2sx47_kube-system(0a6c9800-2873-4368-9dcf-be0659f94b7f)\\\" failed - error: command '/bin/sh -c mv /usrbin/nvidia-container-runtime /usrbin/nvidia-container-runtime-4pdbackup;cp /k8s-vgpu/bin/nvidia-container-runtime /usrbin/;cp -f /k8s-vgpu/lib/* /usr/local/vgpu/' exited with 126: , message: \\\"OCI runtime exec failed: exec failed: cannot exec in a stopped container: unknown\\\\r\\\\n\\\"\"" pod="kube-system/vgpu-device-plugin-2sx47" podUID=0a6c9800-2873-4368-9dcf-be0659f94b7f `
目前看起來是啟動後立即停止，導致一系列cmd運行出錯
想詢問是否遇過以下問題
以及該如何解決
謝謝

補充：
nvidia docker 有重新佈署過，執行官方的測試程序是沒有問題的
`docker run --runtime=nvidia --rm nvidia/cuda:11.0-base nvidia-smi`
![image](https://user-images.githubusercontent.com/32257146/181672039-57c73dc4-5dbd-4e8c-860c-13141576b194.png)
其他的Kubernetes服務也都可以正常佈署

系統資訊：
- system os: ubuntu 20.04
- cluster version: 1.23.4
- docker version: 20.10.7
- nvidia docker2 version: 2.11.0
- k8s-vgpu-schedular version: latest
- nvidia driver version: 515.57
- gpu card: RTX 2060 Super

**Comment by IgerAnes** [comment]
目前初步看起來是執行device-plugin的創建會出問題
所以我執行以下指令
`kubectl logs -n kube-system vgpu-device-plugin-j7xhs device-plugin`
並得出以下結果，顯示/var/lib/4pdvgpu/vgpu.sock在執行時address已經被占用
![image](https://user-images.githubusercontent.com/32257146/182015193-18cf8e95-7e32-44e4-96d7-94d6ecbf2597.png)

目前解決方法：
1. 解除安裝k8s-vgpu-schedular
    `helm uninstall vgpu -n kube-system`
2. 刪除workernode底下的這個檔案
    `rm /var/lib/4pdvgpu/vgpu.sock`
3. 重新安裝k8s-vgpu-schedular

但這只是應急方案
當系統重啟後上述步驟都要重新執行
希望可以改善這個bug

**Comment by archlitchi** [comment]
感谢您提的issue，这个问题出现的原因在于helm卸载时并没有清理干净，目前正在排查原因

**Comment by IgerAnes** [comment]
好的 感謝您的回覆😊
