### ISSUE TITLE
helm install vgpu vgpu -n kube-system 时vgpu-device-plugin没有安装上

### ISSUE THREAD

**Issue by 15220036003** [4paradigm/k8s-vgpu-scheduler#31]
命令执行： helm install vgpu vgpu-charts/vgpu --set devicePlugin.deviceSplitCount=8 --set devicePlugin.deviceMemoryScaling=4 --set scheduler.kubeScheduler.imageTag=v1.20.0 -n kube-system

**Comment by 15220036003** [comment]
![企业微信截图_16601160143779](https://user-images.githubusercontent.com/32127890/183850394-b2a02736-c753-4922-bcd7-ed3bd22db32d.png)
命令执行： helm install vgpu vgpu-charts/vgpu --set devicePlugin.deviceSplitCount=8 --set devicePlugin.deviceMemoryScaling=4 --set scheduler.kubeScheduler.imageTag=v1.20.0 -n kube-system 只安装了vgpu-scheduler,vgpu-device-plugin没有安装上，也找不到pod。这个是什么原因呢？

**Comment by archlitchi** [comment]
你好，请问你给GPU所在的节点打上gpu=on的label了么

**Comment by 15220036003** [comment]
> 你好，请问你给GPU所在的节点打上gpu=on的label了么

打上了的，这个到底是怎么回事？这个问题困扰我好几天了

**Comment by archlitchi** [comment]
你的对应的GPU节点的status是ready的吗，如果是的话，你加我wx：xuanzong4493

**Comment by archlitchi** [comment]
已解决：重新打gpu=on的label，之前未生效原因未知，此先关闭，若有类似问题可以重新打开跟帖
