### ISSUE TITLE
kubelet 没有上报 nvidia.com/gpumem 和 nvidia.com/gpucores

### ISSUE THREAD

**Issue by 51qzpw** [4paradigm/k8s-vgpu-scheduler#40]
使用helm 装完 vgpu 后 使用 kubeclt describe node <gpu-node> 发现只有 nvidia.com/gpu：10 ，并没有 nvidia.com/gpumem 和 nvidia.com/gpucores，在实际使用过程中 无法确认 节点 gpu 剩余的 gpumem

**Comment by archlitchi** [comment]
这个因为不是独立资源所以不能作为设备上报kubelet，如果想要查询余量的话，可以参考节点监控数据

**Comment by cwdsuzhou** [comment]
![image](https://github.com/4paradigm/k8s-vgpu-scheduler/assets/12230714/73424168-6886-4c37-9826-be462f7b82f3)
