### ISSUE TITLE
privileged: true

### ISSUE THREAD

**Issue by wuxiandeng** [4paradigm/k8s-vgpu-scheduler#41]
Pod startup fails when privileged: true is configured in the yaml file

**Comment by archlitchi** [comment]
hi, thanks for your issue, can you tell me the version of vgpu-scheduler?

**Comment by wuxiandeng** [comment]
Version is v1.23.1

Maybe I didn't find the right solution. If there is a solution, please let me know. thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月20日(星期四) 下午2:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [4paradigm/k8s-vgpu-scheduler] privileged: true (Issue #41)





 
hi, thanks for your issue, can you tell me the version of vgpu-scheduler?

**Comment by wuxiandeng** [comment]
Sorry I made a mistake. I said the version of Kubernetes before. I'm not sure about the version of vgpu-scheduler. I installed it using helm: helm install vgpu vgpu charts/vgpu -- set scheduler. kubeScheduler. imageTag=v1.23.1 - n kube system

**Comment by archlitchi** [comment]
ok, i get it. can you provide me with the following information?
1. Is there any error or log of this failed pod?
2. the detail information of this failed pod using 'kubectl describe pod '

**Comment by wuxiandeng** [comment]
The error message is: "0/1 nodes are available: 1 Insufficient nvidia.com/gpucores, 1 Insufficient nvidia.com/gpumem"




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月21日(星期五) 下午3:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [4paradigm/k8s-vgpu-scheduler] privileged: true (Issue #41)





 
ok, i get it. can you provide me with the following information?
  
Is there any error or log of this failed pod?
 
the detail information of this failed pod using 'kubectl describe pod '

**Comment by wuxiandeng** [comment]
I am sure that the resources are sufficient. The error occurs only because "privileged: true" is added.








------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月21日(星期五) 下午3:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [4paradigm/k8s-vgpu-scheduler] privileged: true (Issue #41)





 
ok, i get it. can you provide me with the following information?
  
Is there any error or log of this failed pod?
 
the detail information of this failed pod using 'kubectl describe pod '

**Comment by wuxiandeng** [comment]
1. The resource information is as follows：
Capacity:
  cpu:                24
  ephemeral-storage:  349336928Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             65842544Ki
  nvidia.com/gpu:     20
  pods:               110
Allocatable:
  cpu:                24
  ephemeral-storage:  321948912312
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             65740144Ki
  nvidia.com/gpu:     20
  pods:               110


2. The error message is as follows(info of pod):
Name:           vgpu-58d798dc68-mbl42
Namespace:      default
Priority:       0
Node:           <none>
Labels:         app=vgpu
                pod-template-hash=58d798dc68
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/vgpu-58d798dc68
Containers:
  vgpu:
    Image:      xxl/cuda-centos7:11.7.0-cudnn8-desk-v8
    Port:       6080/TCP
    Host Port:  0/TCP
    Command:
      init
    Limits:
      nvidia.com/gpu:       1
      nvidia.com/gpucores:  10
      nvidia.com/gpumem:    1500
    Requests:
      nvidia.com/gpu:       1
      nvidia.com/gpucores:  10
      nvidia.com/gpumem:    1500
    Environment:
      passwd:  999999
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wqrdz (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  kube-api-access-wqrdz:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  28s (x11 over 11m)  default-scheduler  0/1 nodes are available: 1 Insufficient nvidia.com/gpucores, 1 Insufficient nvidia.com/gpumem.

**Comment by archlitchi** [comment]
Thanks for the information. currently we don't support pod with "privileged=true" containers, because it will always mount ALL GPUs on that node. This issue is embedded in nvidia-docker2, so there's little we can do. you can try the following command on a GPU node in k8s.
`docker run -it --rm --runtime=nvidia -e=NVIDIA_VISIBLE_DEVICES=none ubuntu:18.04 nvidia-smi`
The correct result will be
`No devices were found`
However If you add privilege to this container, like
`docker run -it --rm --runtime=nvidia -e=NVIDIA_VISIBLE_DEVICES=none --privileged ubuntu:18.04 nvidia-smi`
You will see all GPUs even though you assigned 'none' card to it.

However, if you do wish to schedule this 'privileged' GPU pod, here's a way:
1. remove GPU-related resources (nvidia.com/gpu,nvidia.com/gpumem,...) from .pod.spec.containers.resource
2. Add env "NVIDIA_VISIBLE_DEVICES=all" to .pod.spec.containers.env
3. schedule this pod to GPU nodes using nodeselector or nodename
Please note that this pod will be managed by default-kube-scheduler, so, it may cause resource inconsistency between k8s-vgpu-scheduler and node.

**Comment by wuxiandeng** [comment]
Ok, thanks for sharing. I understand.
