### ISSUE TITLE
vgpu-scheduler被分配到非gpu node导致CrashLoopBackOff

### ISSUE THREAD

**Issue by liuzeming-yuxi** [4paradigm/k8s-vgpu-scheduler#45]
vgpu版本:v2.2.5

在将gpu node设置label gpu=true后，虽然vgpu-device-plugin不会在其他node中被创建，但是vgpu-scheduler似乎并没有受该label影响，有概率创建在未设置该label的node中，导致报错nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown

解决方法：将所有非gpu node cordon，重启对应vgpu-scheduler pod，使scheduler强制被分配到gpu node，再uncordon非gpu node

结果：vgpu-scheduler成功运行

似乎该问题是由于scheduler在分配node时未考虑label导致的，请问该问题能否在下个版本修复呢？

**Comment by archlitchi** [comment]
非常感谢您提出的问题，我们会在下个版本进行修复
