### ISSUE TITLE
cuDeviceGetByPCIBusId error when training seresnet34

### ISSUE THREAD

**Issue by liuzeming-yuxi** [4paradigm/k8s-vgpu-scheduler#47]
### Evironment
vgpu version: v2.2.5
os: ubuntu 20.04
python version: 3.8
cuda version: 11.7
gpu memory: 10240
### log info
[trainer0.log](https://github.com/4paradigm/k8s-vgpu-scheduler/files/9936882/trainer0.log)
[trainer1.log](https://github.com/4paradigm/k8s-vgpu-scheduler/files/9936892/trainer1.log)
### error info
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/44457852/199941552-79f9cd36-4938-4fc1-893f-4f8d014d43fd.png">
如上所示，我们使用torchrun去训练seresnet34的时候，cuDeviceGetByPCIBusId出现了一个ERROR，看起来似乎是在cuda层面出现了某些错误，使得Assert failed，请问该错误可能是由于什么导致的呢？

**Comment by archlitchi** [comment]
非常感谢找到bug，此问题已经解决，将在2.2.6中进行修复
