### ISSUE TITLE
Invalid device memory limit: CUDA_DEVICE_SM_LIMIT=0

### ISSUE THREAD

**Issue by Wercurial** [4paradigm/k8s-vgpu-scheduler#48]
![image](https://user-images.githubusercontent.com/43528116/201800352-5b6bd710-422e-4fc5-8428-a5cee972e4b1.png)
请问一下，我在容器中使用的时候，会报很多warning，但是GPU是能正常使用的，安装命令如下
```
 helm install vgpu vgpu-charts/vgpu --set scheduler.kubeScheduler.imageTag=v1.20.10  --set devicePlugin.deviceMemoryScaling=1 --set devicePlugin.deviceSplitCount=2  -n kube-system
```
是因为什么原因呢？

**Comment by archlitchi** [comment]
请问您的版本是多少啊

**Comment by Wercurial** [comment]
> 请问您的版本是多少啊，版本可以见k8s-vdevice的tag

![image](https://user-images.githubusercontent.com/43528116/202672502-7e36b2f3-caf1-4878-9162-7e2e7868e5ef.png)
你好是用的latest版本镜像

**Comment by w-mj** [comment]
我也遇到了这个问题，使用的k8s-vdevice版本为latest
```
[root@gpu1 ~]# docker images | grep k8s
4pdosc/k8s-vdevice                                                   v2.2.6                    7232837d2da2   2 weeks ago     269MB
```

**Comment by Wercurial** [comment]
> 我也遇到了这个问题，使用的k8s-vdevice版本为latest
> 
> ```
> [root@gpu1 ~]# docker images | grep k8s
> 4pdosc/k8s-vdevice                                                   v2.2.6                    7232837d2da2   2 weeks ago     269MB
> ```

推荐你可以先用他们家的k8s-device-plugin 0.9.0.0版本，没有这个bug（4pdosc/k8s-device-plugin:v0.9.0.0）

**Comment by archlitchi** [comment]
@w-mj @Wercurial this issue have been fixed with v2.2.7, please use 'helm repo update' to update

**Comment by Wercurial** [comment]
@w-mj 你好，升级到2.2.7,以后还是同样的报错
![image](https://user-images.githubusercontent.com/43528116/205260336-cd9bef40-2757-48d4-96b9-f665c5728009.png)
![image](https://user-images.githubusercontent.com/43528116/205260386-e1195efc-5f78-45da-9cee-78e106d69f9a.png)

**Comment by archlitchi** [comment]
@Wercurial 这个并不是异常，意思是如果算力限制为0（默认值）的话，就代表不限制算力使用，如果不想看到这条提示的话，可以在业务容器里面加LIBCUDA_LOG_LEVEL=0

后续有任何问题的话欢迎加我wx: xuanzong4493

**Comment by Wercurial** [comment]
@archlitchi 好的，谢谢你了，确实加上环境变量控制日志级别以后就好了
