### ISSUE TITLE
When the gpu cores are not 100, the use of tensor in the gpu will be blocked

### ISSUE THREAD

**Issue by liuzeming-yuxi** [4paradigm/k8s-vgpu-scheduler#49]
VGPU VERSION:v2.2.6
PYTHON VERSION:3.8.10
CUDA VERSION:11.7
NVIDIA/GPU:2
NVIDIA/GPUMEM:6000

As shown in the title，when we use tensor(pytorch) in the gpu,if the gpu cores are not 100, the use of tensor in the gpu will be blocked

NVIDIA/GPUCORES:50
<img width="1001" alt="65d9d5b1502127dd81eabaaf8f7a2868" src="https://user-images.githubusercontent.com/44457852/202196093-70dba7ed-ebb3-4504-9681-d36421364728.png">
NVIDIA/GPUCORES:100
<img width="989" alt="25f3bfaaa0f4a8ec86a8c50cdc046727" src="https://user-images.githubusercontent.com/44457852/202196135-02ae2101-44eb-46e5-b192-2c04ff95152c.png">

What may cause this problem?

**Comment by archlitchi** [comment]
Thanks for this issue, we will fix this bug in v2.2.7

**Comment by archlitchi** [comment]
fixed in v2.28
