### ISSUE TITLE
请问，2.1升级到2.2做了那些修改？为什么升级到2.2以上启动的算法服务都失效了。退回到2.1后正常

### ISSUE THREAD

**Issue by Chenyangzh** [4paradigm/k8s-vgpu-scheduler#51]
如题，将插件从2.0版本升级到2.2.6（最新）后gpu算法服务都失效，查看日志无异常报错，退回到2.2还是不行，退回到2.1后正常。想请问下2.1到2.2做了哪些更新？想看下是否是系统环境配置问题导致异常。

**Comment by archlitchi** [comment]
2.1升级到2.2需要更新chart，因为镜像名称出现了变化，建议完全卸载掉2.1的所有组件之后重新装2.2

**Comment by archlitchi** [comment]
如果还是有问题的话，可以加我wx: xuanzong4493
