### ISSUE TITLE
missing annotation for gpu allocation decision from scheduler

### ISSUE THREAD

**Issue by mzznqt** [4paradigm/k8s-vgpu-scheduler#57]
所有vgpu实例状态正常
![image](https://user-images.githubusercontent.com/49751935/219319354-d8926a18-fea7-44aa-8ce6-c6dcc5f93df3.png)

样例gpu-pod部署之后，提示
Warning  UnexpectedAdmissionError  8m44s      kubelet  Update plugin resources failed due to pod 54e133a1-cb7e-4af8-ac97-46ad084ecd73 missing annotation for gpu allocation decision from scheduler, which is unexpected.

集群版本1.17.17
软件版本2.2.10

附
kube-scheduler log

I0216 08:40:53.539674       1 scheduling_queue.go:841] About to try and schedule pod default/gpu-pod
I0216 08:40:53.539690       1 scheduler.go:606] Attempting to schedule pod: default/gpu-pod
I0216 08:40:53.548100       1 scheduler_binder.go:278] AssumePodVolumes for pod "default/gpu-pod", node "xx"
I0216 08:40:53.548116       1 scheduler_binder.go:288] AssumePodVolumes for pod "default/gpu-pod", node "xx": all PVCs bound and nothing to do
I0216 08:40:53.548664       1 eventhandlers.go:336] Skipping pod default/gpu-pod update
I0216 08:40:53.615368       1 eventhandlers.go:336] Skipping pod default/gpu-pod update
I0216 08:40:53.621364       1 scheduler.go:755] pod default/gpu-pod is bound successfully on node "xx", 1 nodes evaluated, 1 nodes were found feasible.

vgpu-scheduler-extender log

I0216 08:13:37.312943       1 scheduler.go:478] schedule default/gpu-pod to xx [[{GPU-a008xxxx NVIDIA 3000 30} {GPU-d128xxxx NVIDIA 3000 30}]]
I0216 08:13:37.312959       1 pods.go:58] gpu-podAdded
I0216 08:13:37.323315       1 scheduler.go:403] "Bind" pod="gpu-pod" namespace="default" podUID=54e133a1-cb7e-4af8-ac97-46ad084ecd73 node="xx"
I0216 08:13:37.334079       1 nodelock.go:127] "Node lock expired" node="xx" lockTime="2023-02-16 07:55:09 +0000 UTC"
I0216 08:13:37.356406       1 nodelock.go:109] "Node lock released" node="xx"
I0216 08:13:37.382989       1 nodelock.go:77] "Node lock set" node="xx"
I0216 08:13:37.397006       1 scheduler.go:440] After Binding Process
I0216 08:13:37.424838       1 pods.go:67] gpu-pod deleted

**Comment by archlitchi** [comment]
em...只从这些信息可能还没有办法判断出问题，方便加我wx(xuanzong4493)详细了解一下吗

**Comment by mzznqt** [comment]
重新研究了一下，发现是天翼云CCE对k8s集群有定制，针对nvidia.com/gpu这个资源关键字有特殊逻辑，导致调度器无法正常使用
