### ISSUE TITLE
Unable to schedule blue/gpu-pod1

### ISSUE THREAD

**Issue by eadou** [4paradigm/k8s-vgpu-scheduler#6]
当我按照指导安装好后：

```
[root@host-172-21-9-35 gpu]# cat vgpu-test.yaml
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod1
  namespace: blue
spec:
  nodeSelector:
    gpu: "on"
  containers:
  - name: gpu-pod
    image: nvidia/cuda:9.0-base
    command: ["/bin/sh", "-c", "sleep 86400"]
    resources:
      limits:
        nvidia.com/gpu: 3
               nvidia.com/gpumem: 1000
               nvidia.com/gpucores: 30
[root@host-172-21-9-35 gpu]# kubectl create -f vgpu-test.yaml
error: error parsing vgpu-test.yaml: error converting YAML to JSON: yaml: line 16: mapping values are not allowed in this context
```

删除
```
               nvidia.com/gpumem: 1000
               nvidia.com/gpucores: 30
```

后，创建资源，但是一直在pending
```
[root@host-172-21-9-35 gpu]# kubectl get pods -n blue
NAME       READY   STATUS    RESTARTS   AGE
gpu-pod1   0/1     Pending   0          8s
```

查看scheduler的日志信息：
```
[root@host-172-21-9-35 gpu]# kubectl logs -n kube-system vgpu-scheduler-b4f756599-qrh9j kube-scheduler --tail=10
I0124 08:49:33.368916       1 scheduling_queue.go:841] About to try and schedule pod blue/gpu-pod1
I0124 08:49:33.368952       1 scheduler.go:606] Attempting to schedule pod: blue/gpu-pod1
I0124 08:49:33.398379       1 factory.go:453] Unable to schedule blue/gpu-pod1: no fit: 0/5 nodes are available: 4 node(s) didn't match node selector.; waiting
I0124 08:49:33.398456       1 scheduler.go:773] Updating pod condition for blue/gpu-pod1 to (PodScheduled==False, Reason=Unschedulable)
I0124 08:49:33.412627       1 generic_scheduler.go:1212] Node host-172-18-199-14 is a potential node for preemption.
I0124 08:50:58.830278       1 scheduling_queue.go:841] About to try and schedule pod blue/gpu-pod1
I0124 08:50:58.830322       1 scheduler.go:606] Attempting to schedule pod: blue/gpu-pod1
I0124 08:50:58.832585       1 factory.go:453] **Unable to schedule blue/gpu-pod1: no fit: 0/5 nodes are available: 4 node(s) didn't match node selector.; waiting**
I0124 08:50:58.832671       1 scheduler.go:773] Updating pod condition for blue/gpu-pod1 to (PodScheduled==False, Reason=Unschedulable)
I0124 08:50:58.838431       1 generic_scheduler.go:1212] Node host-172-18-199-14 is a potential node for preemption.
```

集群插件pod：
```
[root@host-172-21-9-35 gpu]# kubectl get pods -n kube-system | grep gpu
vgpu-device-plugin-km2r6                         2/2     Running            0          17m
vgpu-scheduler-b4f756599-qrh9j                   2/2     Running            0          17m
```

主机信息：
**gpu 主机信息:**
```
[host-172-18-199-14@root]/root$ rpm -qa | grep nvidia
libnvidia-container1-1.6.0-1.x86_64
nvidia-container-toolkit-1.6.0-1.x86_64
nvidia-container-runtime-3.6.0-1.noarch
nvidia-docker2-2.7.0-1.noarch
libnvidia-container-tools-1.6.0-1.x86_64
```

NVIDIA显卡驱动版本：
NVIDIA-Linux-x86_64-470.82.01.run

docker信息：
```
[host-172-18-199-14@root]/root$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 48
  Running: 28
  Paused: 0
  Stopped: 20
 Images: 25
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: nvidia runc
 Default Runtime: nvidia

```

**Comment by archlitchi** [comment]
请问您的集群GPU分布是什么样子的呢？比如一共有多少个节点，每个节点有几张GPU卡这些～

**Comment by eadou** [comment]
谢谢您的回复。
    目前是在开发环境上测试。集群一共四个节点，其中只有一个GPU节点，此GPU节点上只有一个16G的显卡



***@***.***
 
From: limengxuan
Date: 2022-01-24 19:13
To: 4paradigm/k8s-vgpu-scheduler
CC: eadou; Author
Subject: Re: [4paradigm/k8s-vgpu-scheduler] Unable to schedule blue/gpu-pod1 (Issue #6)
请问您的集群GPU分布是什么样子的呢？比如一共有多少个节点，每个节点有几张GPU卡这些～
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by archlitchi** [comment]
这种情况下，pending的原因在于无法找到一个可以满足需求的执行节点，因为设置的nvidia.com/gpu大小为3，所以要求执行任务的节点上至少要有3个GPU才行。
另外一开始的错误可能是由于缩进错误导致的语法错误， 您可以试一下repo里面的example.yaml

**Comment by eadou** [comment]
nvidia.com/gpu： 3 是指三个物理GPU吗？我理解为是3个vgpu。

那个确实是语法错误，缩进错误。然后我更正了yaml文件，也能运行起来，但是看scheduler的日志报错了。如下：





***@***.***
 
From: limengxuan
Date: 2022-01-25 14:57
To: 4paradigm/k8s-vgpu-scheduler
CC: eadou; Author
Subject: Re: [4paradigm/k8s-vgpu-scheduler] Unable to schedule blue/gpu-pod1 (Issue #6)
这种情况下，pending的原因在于无法找到一个可以满足需求的执行节点，因为设置的nvidia.com/gpu大小为3，所以要求执行任务的节点上至少要有3个GPU才行。
另外一开始的错误可能是由于缩进错误导致的语法错误， 您可以试一下repo里面的example.yaml
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by archlitchi** [comment]
我们的调度器可以提供GPU复用的功能，也就是说可以多个任务复用一张卡，但是无法做到在只有一张卡的节点上跑多卡任务。您这里的错误信息我看不到，可以重新帖一下吗～

**Comment by eadou** [comment]
所以说，指定 nvidia.com/gpu: N  时候，调度器会在满足有N张物理GPU的节点中的一个来启动pod是吗？
    kube-scheduler的日志截图如下，详细日志见附件。





***@***.***
 
From: limengxuan
Date: 2022-01-25 16:49
To: 4paradigm/k8s-vgpu-scheduler
CC: eadou; Author
Subject: Re: [4paradigm/k8s-vgpu-scheduler] Unable to schedule blue/gpu-pod1 (Issue #6)
我们的调度器可以提供GPU复用的功能，也就是说可以多个任务复用一张卡，但是无法做到在只有一张卡的节点上跑多卡任务。您这里的错误信息我看不到，可以重新帖一下吗～
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by eadou** [comment]
您好：

    我的gpu节点，有16G大小的GPU，devicePlugin.deviceMemoryScaling 设置为2，那我可用的GPU内存是不是 2*16=32G 如下图：














***@***.***
 
From: limengxuan
Date: 2022-01-25 16:49
To: 4paradigm/k8s-vgpu-scheduler
CC: eadou; Author
Subject: Re: [4paradigm/k8s-vgpu-scheduler] Unable to schedule blue/gpu-pod1 (Issue #6)
我们的调度器可以提供GPU复用的功能，也就是说可以多个任务复用一张卡，但是无法做到在只有一张卡的节点上跑多卡任务。您这里的错误信息我看不到，可以重新帖一下吗～
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by archlitchi** [comment]
您好，我这边网页版没办法打开您的附件，所以目前看不到问题的具体情况，要不您直接加我wx联系？ wx号：xuanzong4493

**Comment by eadou** [comment]
***@***.***
 
From: limengxuan
Date: 2022-01-26 13:53
To: 4paradigm/k8s-vgpu-scheduler
CC: eadou; Author
Subject: Re: [4paradigm/k8s-vgpu-scheduler] Unable to schedule blue/gpu-pod1 (Issue #6)
您好，我这边网页版没办法打开您的附件，所以目前看不到问题的具体情况，要不您直接加我wx联系？ wx号：xuanzong4493
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
