### ISSUE TITLE
GPU资源使用的整体情况命令

### ISSUE THREAD

**Issue by hellobiek** [4paradigm/k8s-vgpu-scheduler#64]
在使用aliyun的gpushare的方式的时候，会有一个命令，可以查看集群所有的GPU资源整体分配情况。
不知道这里有没有。
kubectl-inspect-gpushare
![image](https://user-images.githubusercontent.com/2854520/233085863-ae60c8ac-c83a-4f55-a59b-bf9cf55260f3.png)

**Comment by archlitchi** [comment]
http://{scheduler node ip}:31993/metrics
