### ISSUE TITLE
调度失败

### ISSUE THREAD

**Issue by hellobiek** [4paradigm/k8s-vgpu-scheduler#75]
想升级，升级后发现docker hub被墙，新版本2.2.14下载不下来，于是回滚，但是回滚失败。

最后根据老版教程安装：https://github.com/4paradigm/k8s-vgpu-scheduler/blob/v2.2.12/README_cn.md

**安装后，调度job失败**
pod.yaml

`kind: Pod
metadata:
name: gpu-pod
namespace: yuepf01
spec:
containers:
- name: ubuntu-container
image: ubuntu:18.04
command: ["bash", "-c", "sleep 86400"]
resources:
limits:
cpu: "1"
memory: "1Gi"
[aliyun.com/gpu-mem](http://aliyun.com/gpu-mem): 1 # 请求2个vGPUs
[nvidia.com/gpumem](http://nvidia.com/gpumem): 1000 # 每个vGPU申请3000m显存 （可选，整数类型）
[nvidia.com/gpucores](http://nvidia.com/gpucores): 0 # 每个vGPU的算力为30%实际显卡的算力 （可选，整数类型）
requests:
cpu: "1"
memory: "1Gi"
#[aliyun.com/gpu-mem](http://aliyun.com/gpu-mem): 1 # 请求2个vGPUs
#[nvidia.com/gpumem](http://nvidia.com/gpumem): 3000 # 每个vGPU申请3000m显存 （可选，整数类型）
#[nvidia.com/gpucores](http://nvidia.com/gpucores): 0 # 每个vGPU的算力为30%实际显卡的算力 （可选，整数类型）`

**但是调度的时候报错：**

db8f8dd-86gkm" err="0/10 nodes are available: 1 node unregisterd, 6 node(s) didn't match Pod's node affinity/selector."

**调整日志级别后，信息如下：**

"Status after running PostFilter plugins for pod" 

pod="llm/chatglm-698d67bff-6f9qh" 

status=&{
code:2 
reasons:[0/10 nodes are available: 
1 No victims found on node zj-b-clab-srv01 for preemptor pod chatglm-698d67bff-6f9qh, 
1 No victims found on node zj-b-clab-srv02 for preemptor pod chatglm-698d67bff-6f9qh, 
1 No victims found on node zj-b-clab-srv03 for preemptor pod chatglm-698d67bff-6f9qh, 
1 No victims found on node zj-b-clab-srv04 for preemptor pod chatglm-698d67bff-6f9qh, 
6 Preemption is not helpful for scheduling.] err:<nil> failedPlugin:}

**Comment by archlitchi** [comment]
已经解决，与api-server有关
