### ISSUE TITLE
Installation failure after update. 版本更新后部署失败

### ISSUE THREAD

**Issue by Chenyangzh** [4paradigm/k8s-vgpu-scheduler#8]
您好，
我正在尝试部署vgpu-scheduler，发现更新后使用helm安装失败，查看日志是kube-scheduler参数错误，如下。

kubectl get pods -A
kube-system   vgpu-device-plugin-k4bjg                   2/2     Running            0               12m
kube-system   vgpu-scheduler-5bc998b64f-bssbm            1/2     CrashLoopBackOff   6 (4m38s ago)   12m

kubectl logs -n kube-system vgpu-scheduler-5bc998b64f-bssbm -c kube-scheduler
Error: unknown flag: --policy-config-file

请问下如何解决？或者如何使用旧版本安装？

**Comment by archlitchi** [comment]
请问您的k8s版本是多少啊

**Comment by Chenyangzh** [comment]
感谢回复！ 我用的kubeadm装的k8s v1.23.1

**Comment by Chenyangzh** [comment]
k8s 降级到v1.16.8问题解决，感谢！
