### ISSUE TITLE
v2.2.16 版本一调度服务vgpu-monitor就重启，请求31992/metrics接口失败

### ISSUE THREAD

**Issue by liuxin638507** [4paradigm/k8s-vgpu-scheduler#80]
k8s 版本:v1.64.4
vgpu版本： k8s-vdevice:v2.2.16 
gpu卡：Tesla T4
![image](https://github.com/4paradigm/k8s-vgpu-scheduler/assets/32058132/575d4798-eb41-41ee-9e20-36ebba9e41e6)
![image](https://github.com/4paradigm/k8s-vgpu-scheduler/assets/32058132/07bb8bad-3372-4569-8adb-c18fe2c88053)

**Comment by archlitchi** [comment]
solved in v2.3.0
