### ISSUE TITLE
显存的显示有bug，使用最新版本

### ISSUE THREAD

**Issue by hellobiek** [4paradigm/k8s-vgpu-scheduler#82]
vgpu的版本为：v2.2.16

pod的容器中和宿主机中展示的gpu使用请款有bug，主要有两点：
1. 训练时指定gpu为3,4 但是在jupyter中显存在0,1GPU上；但是gpu的util显示是正确的。
2. 没有显示占用显存的pid

执行的命令如下：CUDA_VISIBLE_DEVICES=3,4 python -m torch.distributed.launch --nproc_per_node=2 trian_multi_node.py

在jupyter中使用nvidia-smi -l 2 显示结果如下：
![image](https://github.com/4paradigm/k8s-vgpu-scheduler/assets/2854520/bb9428b7-ce01-47e8-a024-c36251e35d75)
但是在宿主机上是正确的：
![image](https://github.com/4paradigm/k8s-vgpu-scheduler/assets/2854520/15e33f5e-3abc-424e-82ae-9b55ac17c8e3)

**Comment by archlitchi** [comment]
solved in v2.3.0
